In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import os

# Ensure reports directory exists
reports_dir = 'reports'
if not os.path.exists(reports_dir):
    os.makedirs(reports_dir)

In [ ]:
# Load Iris Data Once (DRY Principle)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
try:
    # Try local file first
    iris = np.genfromtxt('files/iris.csv', delimiter=',', dtype=object, encoding=None, skip_header=1)
except:
    # Fallback to URL if file doesn't exist
    iris = np.genfromtxt(url, delimiter=',', dtype=object, encoding=None)

# Create numeric version for analysis (first 4 columns)
iris_numbers = iris[:, :4].astype(float)

### Exercise 1

Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.   
Expected Output:

```
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
```

In [ ]:
np.arange(2, 11).reshape(3, 3)


In [ ]:
# Up to you!



### Exercise 2

Write a NumPy program to create a new array of 3*5, filled with 2.   

Expected Output:

```
array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])
```


In [ ]:
np.full((3, 5), 2)


### Exercise 3

Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.  
Expected output:
```
array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])
```

In [ ]:
np.tile(np.arange(0, 5, dtype=float), (5, 1))


### Exercise 4
Write a NumPy program to reverse an array (first element becomes last).  

* Original array:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]  
* Reverse array:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [ ]:
arr = np.arange(12, 38)
arr[::-1]


### Exercise 5
Write a NumPy program to create a 1D array containing 20 random integers between 1 and 6 (included).  
Next filter this array to a new one containing only the odd numbers.

In [ ]:
arr = np.random.randint(1, 7, 20)
odd = arr[arr % 2 != 0]
print(f'Original: {arr}')
print(f'Odd numbers: {odd}')


### Exercise 6
Write a NumPy program to get the positions where elements of a and b match  

Input:  
```
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])  
```

Expected Output:  
```
(array([1, 3, 5, 7]),)
```

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)


### Exercise 7
 Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.   
Checkerboard pattern:  
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
 ```

In [ ]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
matrix


### Exercise 8
 Write a NumPy program to create a 4x4 matrix.  
 Original array:

```
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]
[12 13 14 15]]  
```

* Extract all the elements of the first and fourth rows.  
Expected output:

```
[[ 0,  1,  2,  3], [12, 13, 14, 15]]
```

* Extract all the elements of the first and fourth columns.  
Expected output :

```
[[ 0 3]
[ 4 7]
[ 8 11]
[12 15]]
```

* Extract second and third elements of the second and third rows  
Expected output:

```
[[ 5 6]
[ 9 10]]
```

In [ ]:
matrix = np.arange(16).reshape(4, 4)
print('Full matrix:\n', matrix)
print('Rows 1 & 4:\n', matrix[[0, 3], :])
print('Cols 1 & 4:\n', matrix[:, [0, 3]])
print('Inner 2x2:\n', matrix[1:3, 1:3])


### Exercise 9
Import a dataset with numbers and texts _keeping the text intact_ in a python NumPy array.

The dataset can be found on this url: [https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).  

The data is also available as iris.csv in the files folder.

Each row consists of 5 fields:
* 'sepallength': number
* 'sepalwidth': number
* 'petallength': number
* 'petalwidth': number
* 'species': text

To load this dataset you need to use the genfromtxt() function and make sure that dtype is set to object. Otherwise the 'species' field will contain NaN values.  

Expected output (first 3 rows)
```
array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)
```

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
try:
    iris = np.genfromtxt('files/iris.csv', delimiter=',', dtype=object, encoding=None, skip_header=1)
except:
    iris = np.genfromtxt(url, delimiter=',', dtype=object, encoding=None)
iris[:3]


### Exercise 10
Import the iris dataset again but now just the first four columns.  
Check if there are any missing values in the sepallength (1st column).  
This can be done with the function isnan()  

Expected output:  
Number of missing values: 0  
Position of missing values:
```
(array([], dtype=int64),)
```

Use the commented code in the first block to introduce some missing values. This will help you make sure your code works.

In [ ]:
# Done in the initialization block above
missing_count = np.isnan(iris_numbers[:, 0]).sum()
missing_positions = np.where(np.isnan(iris_numbers[:, 0]))
print(f'Number of missing values: {missing_count}')
print(f'Position of missing values: {missing_positions}')


In [ ]:
# Up to you!



### Exercise 11
Compute the mean, median, standard deviation of iris's sepallength (1st column)  

Expected output:  
```
mean: 5.843333333333334   
median: 5.8   
standard deviation: 0.8253012917851409  
```

In [ ]:
sepallength = iris_numbers[:, 0]
print(f'mean: {np.mean(sepallength)}')
print(f'median: {np.median(sepallength)}')
print(f'standard deviation: {np.std(sepallength)}')


### Exercise 12
Find the 5th and 95th percentile of iris's sepallength.  (1st column)  

Expected output:
```
array([4.6  , 7.255])
```

In [ ]:
np.percentile(iris_numbers[:, 0], [5, 95])


### Exercise 13
Filter the rows in the iris data array that haves petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0  
The resulting array contains the 4 numeric fields for each retrieved row.  

Expected output: 
``` 
array([[4.8, 3.4, 1.6, 0.2],  
       [4.8, 3.4, 1.9, 0.2],  
       [4.7, 3.2, 1.6, 0.2],  
       [4.8, 3.1, 1.6, 0.2],  
       [4.9, 2.4, 3.3, 1. ],  
       [4.9, 2.5, 4.5, 1.7]])
```


In [ ]:
# sepallength (1st col) < 5.0 and petallength (3rd col) > 1.5
condition = (iris_numbers[:, 0] < 5.0) & (iris_numbers[:, 2] > 1.5)
iris_numbers[condition]


### Exercise 14: Data Visualization

To address the feedback about missing graphs, let's visualize the iris data.

In [ ]:
plt.figure(figsize=(10, 6))
plt.scatter(iris_numbers[:, 0], iris_numbers[:, 1], c='blue', alpha=0.5)
plt.title('Iris Sepal Length vs Width')
plt.xlabel('Sepal Length')
plt.ylabel('Sepal Width')
plt.grid(True)
plt.savefig('reports/sepal_scatter.png')  # Save to reports
plt.show()

plt.figure(figsize=(10, 6))
plt.hist(iris_numbers[:, 2], bins=20, color='green', alpha=0.7)
plt.title('Distribution of Petal Length')
plt.xlabel('Petal Length')
plt.ylabel('Frequency')
plt.savefig('reports/petal_distribution.png')  # Save to reports
plt.show()
